### ISSUE TITLE
create a csv file of the stocks to seed the game with

### ISSUE THREAD

**Issue by himleyb85** [himleyb85/recession_survivor#109]
so we don't have to download all the stocks everytime we need to drop the db

**Comment by wmantly** [comment]
No need for a CSV file.

`pg_dump h_trader -t portfolio_stock_history > h_trader_portfolio_stock_history.pg`

To make a SQL file of that table, and

`psql destdb <  h_trader_portfolio_stock_history.pg`

To import it.

**Comment by himleyb85** [comment]
thanks, modified readme to add these instructions
