### ISSUE TITLE
Resume button a tag in game.find.html needs to work

### ISSUE THREAD

**Issue by himleyb85** [himleyb85/recession_survivor#121]

**Comment by himleyb85** [comment]
Things I've tried in the href=

1. {{ "/game/{}/start".format( game.id )}}
2.  in views:  
           request.context_dict['starturl'] = "/game/{}/start"
     in template:  
             {{ starturl|stringformat:game.id }}
3.  {% url 'manage' game.id %}

**Comment by wmantly** [comment]
Ill take a look

**Comment by wmantly** [comment]
fixed in 09858bb
