### ISSUE TITLE
if you're not logged in, the only page that should be assesible is user.index.html

### ISSUE THREAD

**Issue by himleyb85** [himleyb85/recession_survivor#137]
like how in users.views we have:
`class Profile(View):
    def get(self, request):
        if request.user.is_anonymous():
            return redirect( '/')`
so when somebody that's not logged in tries to go to /users/profile they get redirected to the root page.

At least use a function that is just thrown in the class views instead of doing `        if request.user.is_anonymous():
            return redirect( '/')`  every time (not dry), but ideally I'm sure there must be some django specific way of validating authorization by urls.

**Comment by wmantly** [comment]
Linked to #103
