### ISSUE TITLE
Portfolio Object

### ISSUE THREAD

**Issue by wmantly** [himleyb85/recession_survivor#98]
The portfolio needs to be a stand alone object preferably located in its own file( portfolio/portfolio.py ) not entangled in the views.py file.

This is very important for the Games app to be able to use portfolio objects.

**Comment by himleyb85** [comment]
now we just need to switch portfolio being used in game.py to from portfolio.portfolio import Portfolio and adjust all the uses of Portfolio object there

**Comment by wmantly** [comment]
Much progress!
